name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host deploy
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - name: Make temporary directory on server
      run: ssh deploy 'mkdir -p /var/www/timlockridge.com/tmp/'

    - name: SCP files to server
      run: scp -r ./* deploy:/var/www/timlockridge.com/tmp

    - name: Move files and clean up
      run: ssh deploy 'mv /var/www/timlockridge.com/tmp/* /var/www/timlockridge.com/ && rm -rf /var/www/timlockridge.com/tmp/'
